# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc993fe10e779dfb68cefc72747aa616c971bad87ddaee4dd712573e1ec937fd35515f5719ca81d9f2465bc185d989b92ea0d823fbee485b7ad7d1b609241a61

test:
  secret_key_base: 37651f6e0ff01c38f0e60ac83ebf36c7823b8208239bcd840776ae3e9073a8a74de24611812815a7d8e4caec997a7941d3f444a82415d69222fe793160cc0f2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
